version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
     - MYSQL_ROOT_PASSWORD=Aa123456
     - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    network:
      - app-network
  
  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wp_admin
      - WORDPRESS_DB_PASSWORD=Aa123456
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  web:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
#      - ./app:/usr/share/nginx/html
#    links: 
#      - php
    networks:
      - app-network
        #  php: 
        #    image: php:7-fpm
  
volumes: 
   wordpress:
   dbdata:

networks:
  app-network:
    driver: bridge

